# Cursor-compatible + UV-ready
# Run: uv run python utils/seo.py
"""
SEO Utilities - Free keyword extraction and SEO helper functions.
Uses spaCy + YAKE (no paid APIs).
"""

import re
from typing import Optional
from dotenv import load_dotenv

load_dotenv()


class SEOUtils:
    """
    SEO utility functions for keyword research and optimization.
    
    All free — uses YAKE and spaCy locally.
    """

    def __init__(self):
        self._yake = None
        self._nlp = None

    def extract_keywords(
        self,
        text: str,
        top_n: int = 15,
        max_ngram: int = 3,
        language: str = "en",
    ) -> list:
        """
        Extract keywords from text using YAKE algorithm.

        Args:
            text: Input text
            top_n: Number of keywords to return
            max_ngram: Maximum n-gram size (1=single words, 3=phrases)
            language: Language code (default: 'en')

        Returns:
            list of (keyword, relevance_score) tuples
        """
        try:
            import yake
            extractor = yake.KeywordExtractor(
                lan=language,
                n=max_ngram,
                dedupLim=0.7,
                top=top_n,
                features=None,
            )
            keywords = extractor.extract_keywords(text)
            # YAKE: lower score = more relevant
            return sorted(keywords, key=lambda x: x[1])[:top_n]
        except ImportError:
            return self._fallback_keywords(text, top_n)
        except Exception as e:
            print(f"[UV] YAKE extraction error: {e}")
            return self._fallback_keywords(text, top_n)

    def get_keyword_list(self, text: str, top_n: int = 10) -> list:
        """Get just the keyword strings (no scores)."""
        kws = self.extract_keywords(text, top_n=top_n)
        return [kw for kw, _ in kws]

    def calculate_tfidf_keywords(self, texts: list, top_n: int = 10) -> dict:
        """
        Calculate TF-IDF keywords across a corpus of texts.

        Args:
            texts: List of text strings
            top_n: Number of keywords per text

        Returns:
            dict mapping text index to list of keywords
        """
        from collections import Counter
        import math

        # Build corpus word frequencies
        tokenize = lambda t: re.findall(r'\b[a-zA-Z]{3,}\b', t.lower())
        
        stopwords = {
            "the", "and", "for", "are", "but", "not", "you", "all", "can", 
            "her", "was", "one", "our", "had", "has", "his", "they", "have",
            "this", "that", "with", "from", "will", "been", "were", "their",
            "said", "each", "which", "what", "when", "where", "who", "how"
        }
        
        corpus = [set(w for w in tokenize(t) if w not in stopwords) for t in texts]
        
        # IDF calculation
        N = len(texts)
        idf = {}
        all_words = set(w for doc in corpus for w in doc)
        for word in all_words:
            doc_count = sum(1 for doc in corpus if word in doc)
            idf[word] = math.log((N + 1) / (doc_count + 1)) + 1
        
        results = {}
        for i, (text, words) in enumerate(zip(texts, corpus)):
            word_list = [w for w in tokenize(text) if w not in stopwords]
            tf = Counter(word_list)
            total = len(word_list) or 1
            
            scores = {w: (count / total) * idf.get(w, 1) for w, count in tf.items()}
            top_words = sorted(scores.keys(), key=lambda x: scores[x], reverse=True)[:top_n]
            results[i] = top_words
        
        return results

    def generate_meta_tags(self, title: str, description: str, keywords: list) -> str:
        """
        Generate HTML meta tags for SEO.

        Args:
            title: Page title (under 60 chars recommended)
            description: Meta description (150-160 chars recommended)
            keywords: List of target keywords

        Returns:
            str: HTML meta tag block
        """
        kw_string = ", ".join(keywords[:10])
        
        return f"""<!-- SEO Meta Tags (generated by Content Marketing Suite) -->
<title>{title[:60]}</title>
<meta name="description" content="{description[:160]}">
<meta name="keywords" content="{kw_string}">
<meta property="og:title" content="{title[:60]}">
<meta property="og:description" content="{description[:160]}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{title[:60]}">
<meta name="twitter:description" content="{description[:160]}">"""

    def get_related_keywords(self, keyword: str, content: str) -> list:
        """
        Find semantically related keywords from content.
        Uses spaCy noun chunks as related terms.

        Args:
            keyword: Primary keyword
            content: Content to search within

        Returns:
            list of related keyword strings
        """
        try:
            import spacy
            try:
                nlp = spacy.load("en_core_web_sm")
            except OSError:
                return [keyword]
            
            doc = nlp(content[:5000])
            
            # Get noun chunks as related keywords
            chunks = [
                chunk.text.lower().strip()
                for chunk in doc.noun_chunks
                if 2 <= len(chunk.text.split()) <= 4
                and keyword.lower() not in chunk.text.lower()
                and len(chunk.text) > 5
            ]
            
            # Deduplicate and return top related terms
            seen = set()
            related = []
            for chunk in chunks:
                if chunk not in seen:
                    seen.add(chunk)
                    related.append(chunk)
            
            return related[:10]
        except Exception:
            return []

    def suggest_internal_links(self, content: str, pages: list) -> list:
        """
        Suggest internal linking opportunities.

        Args:
            content: The content to analyze
            pages: List of existing page dicts with 'title' and 'url' keys

        Returns:
            list of link suggestions with context
        """
        suggestions = []
        content_lower = content.lower()
        
        for page in pages:
            title = page.get("title", "")
            url = page.get("url", "")
            
            if not title or not url:
                continue
            
            # Check if page topic appears in content
            words = [w.lower() for w in title.split() if len(w) > 4]
            matches = sum(1 for w in words if w in content_lower)
            
            if matches >= len(words) * 0.6:  # 60% word match
                suggestions.append({
                    "page_title": title,
                    "url": url,
                    "relevance": matches / len(words) if words else 0,
                    "anchor_text": title,
                })
        
        return sorted(suggestions, key=lambda x: x["relevance"], reverse=True)[:5]

    def _fallback_keywords(self, text: str, top_n: int) -> list:
        """Simple word frequency fallback if YAKE fails."""
        words = re.findall(r'\b[a-zA-Z]{4,}\b', text.lower())
        stopwords = {"that", "this", "with", "have", "from", "they", "will", "your"}
        freq = {}
        for w in words:
            if w not in stopwords:
                freq[w] = freq.get(w, 0) + 1
        sorted_words = sorted(freq.keys(), key=lambda x: freq[x], reverse=True)[:top_n]
        return [(w, 1.0 / (i + 1)) for i, w in enumerate(sorted_words)]


if __name__ == "__main__":
    utils = SEOUtils()
    
    sample = """
    Content marketing is a strategic marketing approach focused on creating valuable, 
    relevant content to attract and retain customers. AI tools are transforming how 
    marketers create and distribute content at scale.
    """
    
    keywords = utils.extract_keywords(sample, top_n=5)
    print(f"[UV] Top keywords: {[k for k, _ in keywords]}")
    
    meta = utils.generate_meta_tags(
        title="Top AI Content Marketing Tools 2025",
        description="Discover the best AI tools for content marketing in 2025.",
        keywords=[k for k, _ in keywords[:5]],
    )
    print(f"[UV] Generated meta tags:\n{meta}")
